import "dotenv/config";
import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { tools, categories } from "./schema";

const connectionString = process.env.DATABASE_URL;
if (!connectionString) {
  console.error("DATABASE_URL is not set. Create a .env.local file.");
  process.exit(1);
}

const client = postgres(connectionString);
const db = drizzle(client);

const SEED_CATEGORIES = [
  {
    slug: "payments" as const,
    name: "Payments & Commerce",
    description: "Process payments, manage invoices, and handle subscriptions",
    icon: "CreditCard",
    color: "#10B981",
  },
  {
    slug: "communication" as const,
    name: "Communication",
    description: "Send messages, manage channels, and automate outreach",
    icon: "MessageSquare",
    color: "#3B82F6",
  },
  {
    slug: "data" as const,
    name: "Data & Databases",
    description: "Query databases, manage data, and build backends",
    icon: "Database",
    color: "#8B5CF6",
  },
  {
    slug: "devtools" as const,
    name: "Developer Tools",
    description: "Manage repos, track issues, deploy, and monitor",
    icon: "Code",
    color: "#F59E0B",
  },
  {
    slug: "productivity" as const,
    name: "Productivity",
    description: "Calendars, documents, spreadsheets, and project management",
    icon: "Calendar",
    color: "#EC4899",
  },
  {
    slug: "ai-ml" as const,
    name: "AI & ML",
    description: "Access models, run inference, and build AI pipelines",
    icon: "Brain",
    color: "#06B6D4",
  },
  {
    slug: "content" as const,
    name: "Content & Media",
    description: "Images, videos, file management, and media processing",
    icon: "Image",
    color: "#F97316",
  },
  {
    slug: "analytics" as const,
    name: "Analytics",
    description: "Track events, analyze traffic, and measure engagement",
    icon: "BarChart3",
    color: "#6366F1",
  },
];

const now = new Date().toISOString();

const SEED_TOOLS = [
  // ── Official MCP Servers (github.com/modelcontextprotocol/servers) ──
  {
    id: "mcp-filesystem",
    name: "Filesystem",
    slug: "filesystem",
    description: "Secure file operations with configurable access controls for reading, writing, and managing files",
    longDescription:
      "The Filesystem MCP server provides secure access to your local file system through MCP. It allows AI agents to read, write, and manage files and directories with configurable access controls.\n## Key Capabilities\n- Read and write files\n- Create and list directories\n- Move and rename files\n- Search for files by pattern\n- Get file metadata and info\n## Security\n- Configurable root directories limit access scope\n- Path validation prevents directory traversal attacks\n- All operations are sandboxed within allowed paths",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["filesystem", "files", "directories", "io", "local"],
    features: ["Read files", "Write files", "Create directories", "Move/rename files", "Search by pattern", "File metadata"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/filesystem",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#F59E0B",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-filesystem",
  },
  {
    id: "mcp-github",
    name: "GitHub",
    slug: "github",
    description: "Interact with GitHub repositories, issues, pull requests, and more through the GitHub API",
    longDescription:
      "The GitHub MCP server enables AI agents to interact with GitHub's API. Manage repositories, create issues, review pull requests, and automate your development workflow.\n## Key Capabilities\n- Create and manage repositories\n- File operations (create, read, update)\n- Issue and pull request management\n- Branch operations and merging\n- Search across code, issues, and users\n- Fork repositories",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["github", "git", "repositories", "issues", "pull-requests", "ci-cd"],
    features: ["Repo management", "Issue tracking", "PR reviews", "Branch operations", "Code search", "Fork repos"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/github",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#24292E",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-github",
  },
  {
    id: "mcp-gitlab",
    name: "GitLab",
    slug: "gitlab",
    description: "GitLab API integration for managing repositories, merge requests, issues, and CI/CD pipelines",
    longDescription:
      "The GitLab MCP server provides access to the GitLab API through MCP. Manage projects, merge requests, issues, and pipelines with your AI agent.\n## Key Capabilities\n- Create and manage projects\n- Merge request workflows\n- Issue tracking and management\n- File operations in repositories\n- Pipeline and CI/CD interactions",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["gitlab", "git", "merge-requests", "ci-cd", "devops"],
    features: ["Project management", "Merge requests", "Issue tracking", "File operations", "Pipeline management"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gitlab",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#FC6D26",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-gitlab",
  },
  {
    id: "mcp-google-drive",
    name: "Google Drive",
    slug: "google-drive",
    description: "Search and read files from Google Drive, including Docs, Sheets, and PDFs",
    longDescription:
      "The Google Drive MCP server enables AI agents to search and access files stored in Google Drive. It supports reading Google Docs, Sheets, PDFs, and other file types.\n## Key Capabilities\n- Search files across your Drive\n- Read Google Docs content\n- Read Google Sheets data\n- Access PDF files\n- Navigate folder structures",
    category: "productivity" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["google-drive", "files", "documents", "cloud-storage", "google"],
    features: ["File search", "Read Docs", "Read Sheets", "PDF access", "Folder navigation"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#4285F4",
    verified: true,
    trending: false,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-gdrive",
  },
  {
    id: "mcp-slack",
    name: "Slack",
    slug: "slack",
    description: "Interact with Slack workspaces — read channels, post messages, manage conversations",
    longDescription:
      "The Slack MCP server connects your AI agent to Slack workspaces. Read and post messages, manage channels, and search conversations.\n## Key Capabilities\n- List and read channels\n- Post messages to channels\n- Reply to threads\n- Search messages\n- Get user information\n- Manage channel membership",
    category: "communication" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["slack", "messaging", "chat", "channels", "team-communication"],
    features: ["Read channels", "Post messages", "Thread replies", "Search messages", "User info", "Channel management"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/slack",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#4A154B",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-slack",
  },
  {
    id: "mcp-google-maps",
    name: "Google Maps",
    slug: "google-maps",
    description: "Access Google Maps API for geocoding, directions, place search, and distance calculations",
    longDescription:
      "The Google Maps MCP server provides access to Google Maps Platform APIs. Geocode addresses, get directions, search for places, and calculate distances.\n## Key Capabilities\n- Geocode addresses to coordinates\n- Reverse geocoding\n- Get directions between locations\n- Search for places and businesses\n- Calculate distance matrices\n- Place details and reviews",
    category: "data" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["maps", "geocoding", "directions", "places", "google", "location"],
    features: ["Geocoding", "Directions", "Place search", "Distance matrix", "Reverse geocoding", "Place details"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#34A853",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-google-maps",
  },
  {
    id: "mcp-brave-search",
    name: "Brave Search",
    slug: "brave-search",
    description: "Web and local search using the Brave Search API for real-time information retrieval",
    longDescription:
      "The Brave Search MCP server enables AI agents to search the web using Brave's search API. Get real-time search results including web pages, news, and local businesses.\n## Key Capabilities\n- Web search with real-time results\n- Local business search\n- News search\n- Pagination support\n- Result filtering and sorting",
    category: "data" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["search", "web-search", "brave", "information-retrieval"],
    features: ["Web search", "Local search", "News search", "Pagination", "Result filtering"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/brave-search",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#FB542B",
    verified: true,
    trending: true,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-brave-search",
  },
  {
    id: "mcp-fetch",
    name: "Fetch",
    slug: "fetch",
    description: "Fetch and convert web pages to markdown for easy consumption by AI agents",
    longDescription:
      "The Fetch MCP server enables AI agents to retrieve web content and convert it to readable formats. It fetches web pages and converts HTML to markdown for clean consumption.\n## Key Capabilities\n- Fetch any URL\n- HTML to markdown conversion\n- Raw content retrieval\n- Configurable request headers\n- User-agent customization",
    category: "data" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["fetch", "web", "scraping", "markdown", "http"],
    features: ["URL fetching", "HTML to markdown", "Raw content", "Custom headers", "User-agent config"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/fetch",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#6366F1",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-fetch",
  },
  {
    id: "mcp-puppeteer",
    name: "Puppeteer",
    slug: "puppeteer",
    description: "Browser automation and web scraping with Puppeteer for navigation, screenshots, and interaction",
    longDescription:
      "The Puppeteer MCP server provides browser automation capabilities through MCP. Navigate web pages, take screenshots, click elements, fill forms, and extract content.\n## Key Capabilities\n- Navigate to URLs\n- Take screenshots of pages\n- Click elements on pages\n- Fill out forms\n- Execute JavaScript in browser context\n- Extract page content",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["puppeteer", "browser", "automation", "scraping", "screenshots", "testing"],
    features: ["Page navigation", "Screenshots", "Click elements", "Form filling", "JS execution", "Content extraction"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/puppeteer",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#00D8A2",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-puppeteer",
  },
  {
    id: "mcp-postgres",
    name: "PostgreSQL",
    slug: "postgresql",
    description: "Connect to PostgreSQL databases for read-only queries with schema inspection capabilities",
    longDescription:
      "The PostgreSQL MCP server provides read-only access to PostgreSQL databases. Run SQL queries, inspect schemas, list tables, and explore database structure.\n## Key Capabilities\n- Run read-only SQL queries\n- List database tables\n- Describe table schemas\n- Inspect columns and data types\n- Safe query execution with read-only mode",
    category: "data" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["postgresql", "database", "sql", "queries", "postgres"],
    features: ["SQL queries", "Schema inspection", "Table listing", "Column details", "Read-only safety"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/postgres",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#336791",
    verified: true,
    trending: false,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-postgres",
  },
  {
    id: "mcp-sqlite",
    name: "SQLite",
    slug: "sqlite",
    description: "Interact with SQLite databases — create tables, run queries, analyze data, and manage schemas",
    longDescription:
      "The SQLite MCP server provides full access to SQLite databases. Create tables, insert data, run queries, and analyze your data with business intelligence features.\n## Key Capabilities\n- Create and manage tables\n- Run SQL queries (read + write)\n- Insert and update data\n- Schema management\n- Business intelligence memo generation\n- Data analysis",
    category: "data" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["sqlite", "database", "sql", "embedded", "local"],
    features: ["SQL queries", "Table management", "Data insertion", "Schema management", "BI memos", "Data analysis"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#003B57",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-sqlite",
  },
  {
    id: "mcp-memory",
    name: "Memory",
    slug: "memory",
    description: "Persistent memory using a knowledge graph for maintaining context across conversations",
    longDescription:
      "The Memory MCP server provides a persistent knowledge graph that AI agents can use to store and retrieve information across conversations.\n## Key Capabilities\n- Create entities in a knowledge graph\n- Add relations between entities\n- Store observations about entities\n- Query the knowledge graph\n- Delete entities and relations\n- Persistent storage across sessions",
    category: "ai-ml" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["memory", "knowledge-graph", "persistence", "context", "entities"],
    features: ["Entity creation", "Relations", "Observations", "Graph queries", "Persistent storage", "Context management"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/memory",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#06B6D4",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-memory",
  },
  {
    id: "mcp-sequentialthinking",
    name: "Sequential Thinking",
    slug: "sequential-thinking",
    description: "Dynamic problem-solving through structured sequential thinking and thought revision",
    longDescription:
      "The Sequential Thinking MCP server provides a tool for dynamic, reflective problem-solving through a structured thinking process.\n## Key Capabilities\n- Step-by-step thinking process\n- Thought revision and branching\n- Dynamic depth adjustment\n- Hypothesis generation and testing\n- Complex problem decomposition",
    category: "ai-ml" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["thinking", "reasoning", "problem-solving", "ai", "chain-of-thought"],
    features: ["Sequential thinking", "Thought revision", "Branching", "Depth adjustment", "Problem decomposition"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sequentialthinking",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#8B5CF6",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-sequential-thinking",
  },
  {
    id: "mcp-everything",
    name: "Everything",
    slug: "everything",
    description: "Reference MCP server showcasing all protocol features — tools, resources, prompts, and sampling",
    longDescription:
      "The Everything MCP server is a reference implementation that demonstrates all MCP protocol features. It's useful for testing and learning.\n## Key Capabilities\n- Demonstrates all MCP features\n- Example tools, resources, and prompts\n- Sampling demonstration\n- Logging capabilities\n- Reference for building servers",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["reference", "testing", "demo", "mcp-spec", "example"],
    features: ["All MCP features", "Example tools", "Resources demo", "Prompts demo", "Sampling", "Logging"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/everything",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#EF4444",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-everything",
  },
  {
    id: "mcp-sentry",
    name: "Sentry",
    slug: "sentry",
    description: "Retrieve and analyze error data from Sentry for debugging and monitoring applications",
    longDescription:
      "The Sentry MCP server enables AI agents to interact with Sentry for error tracking and monitoring. Retrieve issues, analyze stack traces, and help debug applications.\n## Key Capabilities\n- List Sentry issues\n- Retrieve issue details and events\n- Analyze stack traces\n- Search for errors\n- View project information",
    category: "devtools" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["sentry", "error-tracking", "monitoring", "debugging", "observability"],
    features: ["Issue listing", "Error details", "Stack trace analysis", "Error search", "Project info"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/sentry",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#362D59",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-sentry",
  },

  // ── Popular Community MCP Servers ──
  {
    id: "mcp-stripe",
    name: "Stripe",
    slug: "stripe",
    description: "Interact with the Stripe API for payments, customers, invoices, and subscription management",
    longDescription:
      "The Stripe MCP server connects your AI agent to the Stripe API. Create charges, manage customers, handle subscriptions, and automate payment workflows.\n## Key Capabilities\n- Create and manage customers\n- Process payments and charges\n- Handle subscriptions and plans\n- Create and send invoices\n- Manage payment methods\n- Refund management",
    category: "payments" as const,
    author: { name: "Stripe", username: "stripe", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["stripe", "payments", "billing", "subscriptions", "invoices", "e-commerce"],
    features: ["Payment processing", "Customer management", "Subscriptions", "Invoicing", "Refunds", "Payment methods"],
    githubUrl: "https://github.com/stripe/agent-toolkit",
    docsUrl: "https://docs.stripe.com",
    iconBg: "#635BFF",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@stripe/agent-toolkit",
  },
  {
    id: "mcp-linear",
    name: "Linear",
    slug: "linear",
    description: "Manage Linear issues, projects, and teams through the Linear API for project management",
    longDescription:
      "The Linear MCP server enables AI agents to interact with Linear for project management. Create issues, manage projects, update statuses, and track work.\n## Key Capabilities\n- Create and update issues\n- Manage project workflows\n- Team management\n- Label and priority management\n- Search across issues\n- Cycle and sprint tracking",
    category: "productivity" as const,
    author: { name: "Linear", username: "linearapp", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.5.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["linear", "project-management", "issues", "agile", "workflow"],
    features: ["Issue creation", "Project management", "Team management", "Labels & priorities", "Search", "Cycles"],
    githubUrl: "https://github.com/jerhadf/linear-mcp-server",
    docsUrl: "https://linear.app/docs",
    iconBg: "#5E6AD2",
    verified: false,
    trending: true,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "linear-mcp-server",
  },
  {
    id: "mcp-notion",
    name: "Notion",
    slug: "notion",
    description: "Read, create, and update Notion pages, databases, and blocks through the Notion API",
    longDescription:
      "The Notion MCP server connects your AI agent to Notion workspaces. Search pages, create content, manage databases, and interact with your team's knowledge base.\n## Key Capabilities\n- Search across all Notion pages\n- Create new pages and databases\n- Update existing content\n- Query database entries\n- Manage page properties\n- Block-level content editing",
    category: "productivity" as const,
    author: { name: "Notion Community", username: "notion-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["notion", "wiki", "documents", "databases", "knowledge-base", "notes"],
    features: ["Page search", "Page creation", "Database queries", "Content updates", "Property management", "Block editing"],
    githubUrl: "https://github.com/makenotion/notion-mcp-server",
    docsUrl: "https://developers.notion.com",
    iconBg: "#000000",
    verified: false,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "@notionhq/notion-mcp-server",
  },
  {
    id: "mcp-playwright",
    name: "Playwright",
    slug: "playwright",
    description: "Browser automation with Playwright for web testing, scraping, and UI interaction",
    longDescription:
      "The Playwright MCP server provides advanced browser automation through Microsoft's Playwright framework. Automate web interactions across Chromium, Firefox, and WebKit.\n## Key Capabilities\n- Navigate web pages\n- Take screenshots\n- Click elements and fill forms\n- Execute JavaScript\n- Handle multiple browser contexts\n- Accessibility snapshots",
    category: "devtools" as const,
    author: { name: "Microsoft", username: "microsoft", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.0.20",
    lastUpdated: now,
    createdAt: now,
    tags: ["playwright", "browser", "automation", "testing", "scraping", "microsoft"],
    features: ["Multi-browser", "Screenshots", "Form interaction", "JS execution", "Accessibility", "Page navigation"],
    githubUrl: "https://github.com/microsoft/playwright-mcp",
    docsUrl: "https://playwright.dev",
    iconBg: "#45BA4B",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@anthropic-ai/mcp-server-playwright",
  },
  {
    id: "mcp-supabase",
    name: "Supabase",
    slug: "supabase",
    description: "Manage Supabase projects — databases, auth, storage, edge functions, and more",
    longDescription:
      "The Supabase MCP server gives your AI agent full access to Supabase project management. Query databases, manage auth users, handle storage, and deploy edge functions.\n## Key Capabilities\n- SQL query execution\n- Auth user management\n- Storage bucket operations\n- Edge function management\n- Project configuration\n- Database schema management",
    category: "data" as const,
    author: { name: "Supabase", username: "supabase", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["supabase", "database", "auth", "storage", "postgres", "backend"],
    features: ["SQL queries", "Auth management", "Storage ops", "Edge functions", "Project config", "Schema management"],
    githubUrl: "https://github.com/supabase-community/supabase-mcp",
    docsUrl: "https://supabase.com/docs",
    iconBg: "#3ECF8E",
    verified: true,
    trending: true,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "supabase-mcp-server",
  },
  {
    id: "mcp-cloudflare",
    name: "Cloudflare",
    slug: "cloudflare",
    description: "Manage Cloudflare Workers, KV, R2, and D1 resources through the Cloudflare API",
    longDescription:
      "The Cloudflare MCP server enables AI agents to manage Cloudflare infrastructure. Deploy Workers, manage KV stores, interact with R2 storage, and query D1 databases.\n## Key Capabilities\n- Deploy and manage Workers\n- KV namespace operations\n- R2 storage management\n- D1 database queries\n- DNS management\n- Worker logs and analytics",
    category: "devtools" as const,
    author: { name: "Cloudflare", username: "cloudflare", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["cloudflare", "workers", "edge", "kv", "r2", "d1", "cdn"],
    features: ["Workers deploy", "KV operations", "R2 storage", "D1 queries", "DNS management", "Analytics"],
    githubUrl: "https://github.com/cloudflare/mcp-server-cloudflare",
    docsUrl: "https://developers.cloudflare.com",
    iconBg: "#F38020",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@cloudflare/mcp-server-cloudflare",
  },
  {
    id: "mcp-vercel",
    name: "Vercel",
    slug: "vercel",
    description: "Manage Vercel deployments, projects, domains, and environment variables",
    longDescription:
      "The Vercel MCP server connects AI agents to the Vercel platform. Manage deployments, configure projects, handle domains, and set environment variables.\n## Key Capabilities\n- List and manage deployments\n- Project configuration\n- Domain management\n- Environment variable management\n- Deployment logs\n- Team management",
    category: "devtools" as const,
    author: { name: "Vercel Community", username: "vercel-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.2.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["vercel", "deployment", "hosting", "nextjs", "serverless"],
    features: ["Deployment management", "Project config", "Domain management", "Env variables", "Deployment logs", "Teams"],
    githubUrl: "https://github.com/nichochar/vercel-mcp-server",
    docsUrl: "https://vercel.com/docs",
    iconBg: "#000000",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "vercel-mcp-server",
  },
  {
    id: "mcp-docker",
    name: "Docker",
    slug: "docker",
    description: "Manage Docker containers, images, volumes, and networks through the Docker Engine API",
    longDescription:
      "The Docker MCP server enables AI agents to manage Docker resources. List containers, run images, manage volumes, and interact with the Docker engine.\n## Key Capabilities\n- List and manage containers\n- Pull and manage images\n- Create and inspect volumes\n- Network management\n- Container logs\n- Docker Compose support",
    category: "devtools" as const,
    author: { name: "Docker Community", username: "docker-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["docker", "containers", "devops", "deployment", "infrastructure"],
    features: ["Container management", "Image management", "Volume management", "Networking", "Logs", "Compose"],
    githubUrl: "https://github.com/ckreiling/mcp-server-docker",
    docsUrl: "https://docs.docker.com",
    iconBg: "#2496ED",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "mcp-server-docker",
  },
  {
    id: "mcp-todoist",
    name: "Todoist",
    slug: "todoist",
    description: "Manage Todoist tasks, projects, and labels for personal and team productivity",
    longDescription:
      "The Todoist MCP server connects AI agents to Todoist for task management. Create tasks, organize projects, set due dates, and manage your workflow.\n## Key Capabilities\n- Create and update tasks\n- Project management\n- Label and filter management\n- Due date handling\n- Priority settings\n- Task completion tracking",
    category: "productivity" as const,
    author: { name: "Todoist Community", username: "todoist-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.3.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["todoist", "tasks", "todo", "productivity", "project-management"],
    features: ["Task creation", "Projects", "Labels", "Due dates", "Priorities", "Completion tracking"],
    githubUrl: "https://github.com/abhiz123/todoist-mcp-server",
    docsUrl: "https://developer.todoist.com",
    iconBg: "#E44332",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "todoist-mcp-server",
  },
  {
    id: "mcp-raygun",
    name: "Raygun",
    slug: "raygun",
    description: "Access crash reporting and real user monitoring data from Raygun for application debugging",
    longDescription:
      "The Raygun MCP server enables AI agents to access Raygun's error tracking and performance monitoring data for debugging and analysis.\n## Key Capabilities\n- Retrieve crash reports\n- Access error group details\n- Real user monitoring data\n- Performance metrics\n- Application health overview",
    category: "analytics" as const,
    author: { name: "Raygun", username: "MindscapeHQ", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["raygun", "error-tracking", "monitoring", "performance", "rum"],
    features: ["Crash reports", "Error groups", "RUM data", "Performance metrics", "Health overview"],
    githubUrl: "https://github.com/MindscapeHQ/mcp-server-raygun",
    docsUrl: "https://raygun.com/documentation",
    iconBg: "#4F46E5",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "@anthropic-ai/mcp-server-raygun",
  },
  {
    id: "mcp-twilio",
    name: "Twilio",
    slug: "twilio",
    description: "Send SMS messages, make calls, and manage communication workflows through the Twilio API",
    longDescription:
      "The Twilio MCP server enables AI agents to interact with Twilio's communication APIs. Send SMS, make voice calls, and manage messaging workflows.\n## Key Capabilities\n- Send SMS messages\n- Make voice calls\n- Manage phone numbers\n- Message history\n- Webhook management\n- Communication workflows",
    category: "communication" as const,
    author: { name: "Twilio Community", username: "twilio-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["twilio", "sms", "voice", "messaging", "communication"],
    features: ["Send SMS", "Voice calls", "Phone numbers", "Message history", "Webhooks", "Workflows"],
    githubUrl: "https://github.com/twilio-labs/mcp-server-twilio",
    docsUrl: "https://www.twilio.com/docs",
    iconBg: "#F22F46",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "@anthropic-ai/mcp-server-twilio",
  },
  {
    id: "mcp-email",
    name: "Email (SMTP)",
    slug: "email-smtp",
    description: "Send emails via SMTP with support for HTML content, attachments, and multiple providers",
    longDescription:
      "The Email MCP server enables AI agents to send emails through SMTP. Supports Gmail, Outlook, and any SMTP provider with HTML content and attachments.\n## Key Capabilities\n- Send emails via SMTP\n- HTML email content\n- File attachments\n- Multiple recipients (To, CC, BCC)\n- Custom SMTP providers\n- Template support",
    category: "communication" as const,
    author: { name: "MCP Community", username: "mcp-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["email", "smtp", "gmail", "outlook", "messaging"],
    features: ["Send emails", "HTML content", "Attachments", "CC/BCC", "SMTP providers", "Templates"],
    githubUrl: "https://github.com/mcp-tools/mcp-server-email",
    docsUrl: null,
    iconBg: "#EA4335",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-discord",
    name: "Discord",
    slug: "discord",
    description: "Interact with Discord servers — send messages, manage channels, and handle server operations",
    longDescription:
      "The Discord MCP server connects AI agents to Discord for server management and messaging. Send messages, manage channels, and interact with Discord communities.\n## Key Capabilities\n- Send messages to channels\n- Read message history\n- Manage channels\n- Server information\n- User lookup\n- Thread management",
    category: "communication" as const,
    author: { name: "Discord Community", username: "discord-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["discord", "chat", "messaging", "community", "bots"],
    features: ["Send messages", "Read history", "Channel management", "Server info", "User lookup", "Threads"],
    githubUrl: "https://github.com/v-3/discordmcp",
    docsUrl: "https://discord.com/developers/docs",
    iconBg: "#5865F2",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-shopify",
    name: "Shopify",
    slug: "shopify",
    description: "Manage Shopify stores — products, orders, customers, and inventory through the Shopify API",
    longDescription:
      "The Shopify MCP server connects AI agents to Shopify stores. Manage products, process orders, handle customers, and track inventory.\n## Key Capabilities\n- Product management (CRUD)\n- Order processing and tracking\n- Customer management\n- Inventory management\n- Collection management\n- Storefront data access",
    category: "payments" as const,
    author: { name: "Shopify Community", username: "shopify-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["shopify", "e-commerce", "products", "orders", "inventory"],
    features: ["Product CRUD", "Order tracking", "Customer management", "Inventory", "Collections", "Storefront"],
    githubUrl: "https://github.com/shopify/shopify-mcp-server",
    docsUrl: "https://shopify.dev",
    iconBg: "#96BF48",
    verified: false,
    trending: false,
    featured: true,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-paypal",
    name: "PayPal",
    slug: "paypal",
    description: "Process payments, manage transactions, and handle refunds through the PayPal API",
    longDescription:
      "The PayPal MCP server enables AI agents to interact with PayPal's payment platform. Process payments, manage transactions, and handle disputes.\n## Key Capabilities\n- Process payments\n- Manage invoices\n- Handle refunds\n- Transaction history\n- Dispute management\n- Subscription billing",
    category: "payments" as const,
    author: { name: "PayPal Community", username: "paypal-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["paypal", "payments", "invoices", "transactions", "refunds"],
    features: ["Payments", "Invoices", "Refunds", "Transaction history", "Disputes", "Subscriptions"],
    githubUrl: "https://github.com/nichochar/paypal-mcp-server",
    docsUrl: "https://developer.paypal.com",
    iconBg: "#003087",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-square",
    name: "Square",
    slug: "square",
    description: "Connect to Square for payment processing, catalog management, and point-of-sale operations",
    longDescription:
      "The Square MCP server connects AI agents to Square's platform for payment processing and business management. Handle payments, manage catalog items, and access POS data.\n## Key Capabilities\n- Payment processing\n- Catalog management\n- Customer management\n- Order management\n- Location management\n- Inventory tracking",
    category: "payments" as const,
    author: { name: "Square Community", username: "square-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["square", "payments", "pos", "catalog", "commerce"],
    features: ["Payments", "Catalog", "Customers", "Orders", "Locations", "Inventory"],
    githubUrl: "https://github.com/square/square-mcp-server",
    docsUrl: "https://developer.squareup.com",
    iconBg: "#006AFF",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-firecrawl",
    name: "Firecrawl",
    slug: "firecrawl",
    description: "Web scraping and crawling with Firecrawl — extract structured data from any website",
    longDescription:
      "The Firecrawl MCP server enables AI agents to scrape and crawl websites for structured data extraction. Convert web pages to clean markdown and extract specific data.\n## Key Capabilities\n- Scrape single pages\n- Crawl entire websites\n- Extract structured data\n- Markdown conversion\n- Screenshot capture\n- Map website structure",
    category: "data" as const,
    author: { name: "Firecrawl", username: "mendableai", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["firecrawl", "scraping", "crawling", "web", "data-extraction"],
    features: ["Page scraping", "Website crawling", "Structured data", "Markdown output", "Screenshots", "Site mapping"],
    githubUrl: "https://github.com/mendableai/firecrawl-mcp-server",
    docsUrl: "https://docs.firecrawl.dev",
    iconBg: "#FF6B35",
    verified: true,
    trending: true,
    featured: true,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "firecrawl-mcp",
  },
  {
    id: "mcp-exa",
    name: "Exa Search",
    slug: "exa-search",
    description: "AI-native search engine that finds content semantically — perfect for research and knowledge work",
    longDescription:
      "The Exa MCP server provides AI-native search capabilities. Search the web semantically, find similar pages, and get highlighted content for research.\n## Key Capabilities\n- Semantic web search\n- Find similar pages\n- Content highlighting\n- Neural search mode\n- Keyword search mode\n- Result filtering by domain/date",
    category: "ai-ml" as const,
    author: { name: "Exa", username: "exa-labs", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["exa", "search", "semantic-search", "ai-search", "research"],
    features: ["Semantic search", "Similar pages", "Content highlighting", "Neural mode", "Keyword mode", "Filtering"],
    githubUrl: "https://github.com/exa-labs/exa-mcp-server",
    docsUrl: "https://docs.exa.ai",
    iconBg: "#1a1a2e",
    verified: true,
    trending: true,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "exa-mcp-server",
  },
  {
    id: "mcp-neon",
    name: "Neon",
    slug: "neon",
    description: "Manage Neon serverless Postgres — databases, branches, roles, and SQL execution",
    longDescription:
      "The Neon MCP server enables AI agents to manage Neon serverless Postgres databases. Create branches, run SQL, manage roles, and handle database operations.\n## Key Capabilities\n- Create and manage database branches\n- Execute SQL queries\n- Role management\n- Project management\n- Connection string retrieval\n- Database migrations",
    category: "data" as const,
    author: { name: "Neon", username: "neondatabase", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["neon", "postgres", "serverless", "database", "branching"],
    features: ["Branch management", "SQL execution", "Role management", "Project management", "Connection strings", "Migrations"],
    githubUrl: "https://github.com/neondatabase/mcp-server-neon",
    docsUrl: "https://neon.tech/docs",
    iconBg: "#00E699",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "mcp-server-neon",
  },
  {
    id: "mcp-upstash",
    name: "Upstash",
    slug: "upstash",
    description: "Access Upstash Redis and QStash for serverless caching, rate limiting, and message queues",
    longDescription:
      "The Upstash MCP server provides access to Upstash's serverless Redis and QStash services. Handle caching, rate limiting, and async messaging.\n## Key Capabilities\n- Redis command execution\n- Key-value operations\n- QStash message publishing\n- Rate limiting\n- Cache management\n- Pub/sub messaging",
    category: "data" as const,
    author: { name: "Upstash", username: "upstash", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["upstash", "redis", "qstash", "cache", "serverless", "messaging"],
    features: ["Redis commands", "Key-value ops", "QStash messaging", "Rate limiting", "Caching", "Pub/sub"],
    githubUrl: "https://github.com/upstash/mcp-server",
    docsUrl: "https://upstash.com/docs",
    iconBg: "#00E9A3",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-airtable",
    name: "Airtable",
    slug: "airtable",
    description: "Read and write Airtable bases, tables, and records for spreadsheet-database hybrid workflows",
    longDescription:
      "The Airtable MCP server enables AI agents to interact with Airtable bases. List records, create entries, update fields, and manage your data tables.\n## Key Capabilities\n- List tables and fields\n- Read records with filtering\n- Create new records\n- Update existing records\n- Delete records\n- Search across bases",
    category: "productivity" as const,
    author: { name: "Airtable Community", username: "airtable-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.2.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["airtable", "spreadsheet", "database", "tables", "records"],
    features: ["List records", "Create records", "Update records", "Delete records", "Field management", "Search"],
    githubUrl: "https://github.com/domdomegg/airtable-mcp-server",
    docsUrl: "https://airtable.com/developers",
    iconBg: "#18BFFF",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "airtable-mcp-server",
  },
  {
    id: "mcp-obsidian",
    name: "Obsidian",
    slug: "obsidian",
    description: "Read, search, and manage Obsidian vaults for personal knowledge management and note-taking",
    longDescription:
      "The Obsidian MCP server connects AI agents to Obsidian vaults. Read notes, search content, create new documents, and manage your knowledge graph.\n## Key Capabilities\n- Read notes from vault\n- Search across all notes\n- Create new notes\n- Update existing notes\n- List vault structure\n- Tag management",
    category: "productivity" as const,
    author: { name: "Obsidian Community", username: "obsidian-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["obsidian", "notes", "markdown", "knowledge-base", "pkm"],
    features: ["Read notes", "Search vault", "Create notes", "Update notes", "Vault structure", "Tags"],
    githubUrl: "https://github.com/smithery-ai/mcp-obsidian",
    docsUrl: "https://obsidian.md",
    iconBg: "#7C3AED",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "mcp-obsidian",
  },
  {
    id: "mcp-youtube-transcript",
    name: "YouTube Transcript",
    slug: "youtube-transcript",
    description: "Extract transcripts and captions from YouTube videos for content analysis and summarization",
    longDescription:
      "The YouTube Transcript MCP server enables AI agents to extract transcripts from YouTube videos. Get captions, timestamps, and full video transcripts.\n## Key Capabilities\n- Extract video transcripts\n- Get captions with timestamps\n- Support for multiple languages\n- Automatic caption detection\n- Full text extraction",
    category: "content" as const,
    author: { name: "YouTube MCP Community", username: "youtube-mcp", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["youtube", "transcripts", "captions", "video", "content"],
    features: ["Transcript extraction", "Timestamped captions", "Multi-language", "Auto-captions", "Full text"],
    githubUrl: "https://github.com/kimtaeyoon83/mcp-server-youtube-transcript",
    docsUrl: null,
    iconBg: "#FF0000",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "mcp-server-youtube-transcript",
  },
  {
    id: "mcp-unsplash",
    name: "Unsplash",
    slug: "unsplash",
    description: "Search and download high-quality photos from Unsplash for content creation and design",
    longDescription:
      "The Unsplash MCP server enables AI agents to search and access the Unsplash photo library. Find images by keyword, get photo details, and download high-quality images.\n## Key Capabilities\n- Search photos by keyword\n- Get photo details and metadata\n- Download URLs in various sizes\n- Access photographer information\n- Browse curated collections\n- Random photo retrieval",
    category: "content" as const,
    author: { name: "Unsplash Community", username: "unsplash-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["unsplash", "images", "photos", "stock-photos", "design"],
    features: ["Photo search", "Photo details", "Download URLs", "Photographer info", "Collections", "Random photos"],
    githubUrl: "https://github.com/nichochar/unsplash-mcp-server",
    docsUrl: "https://unsplash.com/documentation",
    iconBg: "#000000",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-time",
    name: "Time",
    slug: "time",
    description: "Get current time and do timezone conversions for scheduling and time-aware operations",
    longDescription:
      "The Time MCP server provides time-related tools for AI agents. Get the current time in any timezone and convert between timezones.\n## Key Capabilities\n- Get current time in any timezone\n- Convert between timezones\n- List available timezones\n- UTC offset information\n- ISO 8601 formatting",
    category: "productivity" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["time", "timezone", "clock", "scheduling", "utc"],
    features: ["Current time", "Timezone conversion", "Timezone list", "UTC offsets", "ISO 8601"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/time",
    docsUrl: "https://modelcontextprotocol.io/docs",
    iconBg: "#6366F1",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-time",
  },
  {
    id: "mcp-aws-kb-retrieval",
    name: "AWS KB Retrieval",
    slug: "aws-kb-retrieval",
    description: "Retrieve information from AWS Knowledge Bases using Amazon Bedrock for RAG applications",
    longDescription:
      "The AWS Knowledge Base Retrieval MCP server enables AI agents to query AWS Knowledge Bases powered by Amazon Bedrock. Retrieve relevant documents and passages for RAG workflows.\n## Key Capabilities\n- Query knowledge bases\n- Retrieve relevant passages\n- Semantic search\n- Document ranking\n- Configurable result count",
    category: "ai-ml" as const,
    author: { name: "Anthropic", username: "modelcontextprotocol", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.6.2",
    lastUpdated: now,
    createdAt: now,
    tags: ["aws", "bedrock", "rag", "knowledge-base", "retrieval"],
    features: ["KB queries", "Passage retrieval", "Semantic search", "Document ranking", "Configurable results"],
    githubUrl: "https://github.com/modelcontextprotocol/servers/tree/main/src/aws-kb-retrieval-server",
    docsUrl: "https://docs.aws.amazon.com/bedrock",
    iconBg: "#FF9900",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "@modelcontextprotocol/server-aws-kb-retrieval",
  },
  {
    id: "mcp-openai",
    name: "OpenAI",
    slug: "openai",
    description: "Access OpenAI models for text generation, embeddings, and image generation via the OpenAI API",
    longDescription:
      "The OpenAI MCP server provides access to OpenAI's API through MCP. Generate text, create embeddings, and generate images with GPT and DALL-E models.\n## Key Capabilities\n- Text generation with GPT models\n- Text embeddings\n- Image generation with DALL-E\n- Model selection\n- Token counting\n- Streaming responses",
    category: "ai-ml" as const,
    author: { name: "OpenAI Community", username: "openai-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.2.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["openai", "gpt", "dalle", "embeddings", "ai", "llm"],
    features: ["Text generation", "Embeddings", "Image generation", "Model selection", "Token counting", "Streaming"],
    githubUrl: "https://github.com/nichochar/openai-mcp-server",
    docsUrl: "https://platform.openai.com/docs",
    iconBg: "#412991",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-cloudinary",
    name: "Cloudinary",
    slug: "cloudinary",
    description: "Upload, transform, and manage images and videos with Cloudinary's media management platform",
    longDescription:
      "The Cloudinary MCP server connects AI agents to Cloudinary for media management. Upload images, apply transformations, manage assets, and optimize media delivery.\n## Key Capabilities\n- Upload images and videos\n- Apply transformations\n- Manage media assets\n- Search assets\n- Generate delivery URLs\n- Optimize media",
    category: "content" as const,
    author: { name: "Cloudinary", username: "cloudinary", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["cloudinary", "images", "video", "media", "cdn", "optimization"],
    features: ["Upload media", "Transformations", "Asset management", "Search", "Delivery URLs", "Optimization"],
    githubUrl: "https://github.com/cloudinary/cloudinary-mcp-server",
    docsUrl: "https://cloudinary.com/documentation",
    iconBg: "#3448C5",
    verified: true,
    trending: false,
    featured: true,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "cloudinary-mcp-server",
  },
  {
    id: "mcp-posthog",
    name: "PostHog",
    slug: "posthog",
    description: "Query product analytics, feature flags, and user data from PostHog for insights and analysis",
    longDescription:
      "The PostHog MCP server connects AI agents to PostHog for product analytics. Query events, manage feature flags, access user data, and analyze product metrics.\n## Key Capabilities\n- Query analytics events\n- Manage feature flags\n- Access user profiles\n- Trend analysis\n- Funnel analysis\n- Cohort management",
    category: "analytics" as const,
    author: { name: "PostHog", username: "posthog", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["posthog", "analytics", "product-analytics", "feature-flags", "events"],
    features: ["Event queries", "Feature flags", "User profiles", "Trend analysis", "Funnels", "Cohorts"],
    githubUrl: "https://github.com/PostHog/posthog-mcp",
    docsUrl: "https://posthog.com/docs",
    iconBg: "#F9BD2B",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-mixpanel",
    name: "Mixpanel",
    slug: "mixpanel",
    description: "Query Mixpanel analytics data for user behavior analysis, funnels, and retention metrics",
    longDescription:
      "The Mixpanel MCP server enables AI agents to query Mixpanel analytics. Analyze user behavior, build funnels, measure retention, and extract insights.\n## Key Capabilities\n- Event analytics queries\n- Funnel analysis\n- Retention metrics\n- User segmentation\n- Property analysis\n- JQL queries",
    category: "analytics" as const,
    author: { name: "Mixpanel Community", username: "mixpanel-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["mixpanel", "analytics", "user-behavior", "funnels", "retention"],
    features: ["Event analytics", "Funnels", "Retention", "Segmentation", "Properties", "JQL"],
    githubUrl: "https://github.com/nichochar/mixpanel-mcp-server",
    docsUrl: "https://developer.mixpanel.com",
    iconBg: "#7856FF",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-context7",
    name: "Context7",
    slug: "context7",
    description: "Fetch up-to-date documentation and code examples for any library directly into your AI context",
    longDescription:
      "Context7 MCP server provides up-to-date, version-specific documentation and code examples for libraries and frameworks. No more outdated knowledge or hallucinated APIs.\n## Key Capabilities\n- Fetch library documentation\n- Version-specific content\n- Code examples\n- API references\n- Framework guides\n- Real-time updates",
    category: "devtools" as const,
    author: { name: "Context7", username: "context7", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["documentation", "libraries", "api-reference", "code-examples", "context"],
    features: ["Library docs", "Version-specific", "Code examples", "API references", "Framework guides", "Real-time"],
    githubUrl: "https://github.com/context-7/context7",
    docsUrl: "https://context7.com",
    iconBg: "#000000",
    verified: false,
    trending: true,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "context7-mcp",
  },
  {
    id: "mcp-smithery",
    name: "Smithery",
    slug: "smithery",
    description: "Discover and use MCP servers from Smithery's registry — a meta-server for the MCP ecosystem",
    longDescription:
      "Smithery MCP server acts as a meta-server that connects you to other MCP servers from the Smithery registry. Browse, discover, and use MCP tools dynamically.\n## Key Capabilities\n- Browse MCP server registry\n- Dynamic server connections\n- Server search\n- Server metadata\n- Usage statistics",
    category: "devtools" as const,
    author: { name: "Smithery", username: "smithery-ai", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["smithery", "registry", "mcp-servers", "discovery", "meta"],
    features: ["Server registry", "Dynamic connections", "Server search", "Metadata", "Usage stats"],
    githubUrl: "https://github.com/smithery-ai/mcp-server-smithery",
    docsUrl: "https://smithery.ai",
    iconBg: "#1E293B",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@anthropic-ai/mcp-server-smithery",
  },
  {
    id: "mcp-google-calendar",
    name: "Google Calendar",
    slug: "google-calendar",
    description: "Manage Google Calendar events — create, update, delete, and query calendar entries",
    longDescription:
      "The Google Calendar MCP server enables AI agents to manage Google Calendar. Create events, check availability, update schedules, and manage multiple calendars.\n## Key Capabilities\n- Create calendar events\n- Update existing events\n- Delete events\n- Check free/busy status\n- List calendars\n- Search events",
    category: "productivity" as const,
    author: { name: "Google Calendar Community", username: "gcal-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["google-calendar", "calendar", "events", "scheduling", "google"],
    features: ["Create events", "Update events", "Delete events", "Free/busy", "List calendars", "Search"],
    githubUrl: "https://github.com/nspady/google-calendar-mcp",
    docsUrl: "https://developers.google.com/calendar",
    iconBg: "#4285F4",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-telegram",
    name: "Telegram",
    slug: "telegram",
    description: "Send and receive Telegram messages, manage groups, and interact with the Telegram Bot API",
    longDescription:
      "The Telegram MCP server connects AI agents to Telegram through the Bot API. Send messages, manage groups, handle inline queries, and automate Telegram workflows.\n## Key Capabilities\n- Send messages\n- Receive updates\n- Group management\n- Inline queries\n- Media sending\n- Keyboard menus",
    category: "communication" as const,
    author: { name: "Telegram Community", username: "telegram-community", verified: false },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["telegram", "messaging", "bots", "chat", "groups"],
    features: ["Send messages", "Receive updates", "Groups", "Inline queries", "Media", "Keyboards"],
    githubUrl: "https://github.com/nichochar/telegram-mcp-server",
    docsUrl: "https://core.telegram.org/bots/api",
    iconBg: "#0088CC",
    verified: false,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: null,
  },
  {
    id: "mcp-browserbase",
    name: "Browserbase",
    slug: "browserbase",
    description: "Cloud browser automation with Browserbase — run headless browsers at scale for web tasks",
    longDescription:
      "The Browserbase MCP server provides cloud-based browser automation. Run headless browsers at scale without managing infrastructure.\n## Key Capabilities\n- Cloud headless browsers\n- Navigate web pages\n- Take screenshots\n- Extract content\n- Form interaction\n- Session management",
    category: "devtools" as const,
    author: { name: "Browserbase", username: "browserbase", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "1.0.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["browserbase", "browser", "headless", "automation", "cloud"],
    features: ["Cloud browsers", "Page navigation", "Screenshots", "Content extraction", "Forms", "Sessions"],
    githubUrl: "https://github.com/browserbase/mcp-server-browserbase",
    docsUrl: "https://docs.browserbase.com",
    iconBg: "#FF6600",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Gemini", "Open Source"],
    npmPackage: "@anthropic-ai/mcp-server-browserbase",
  },
  {
    id: "mcp-tinybird",
    name: "Tinybird",
    slug: "tinybird",
    description: "Query real-time analytics data from Tinybird — serverless ClickHouse for event-driven analytics",
    longDescription:
      "The Tinybird MCP server enables AI agents to query Tinybird analytics endpoints. Access real-time data, run SQL queries, and analyze streaming data.\n## Key Capabilities\n- Query analytics endpoints\n- Run SQL queries\n- Access real-time data\n- Data source management\n- Pipe management\n- Token management",
    category: "analytics" as const,
    author: { name: "Tinybird", username: "tinybirdco", verified: true },
    pricing: { model: "free" as const },
    rating: 0,
    reviewCount: 0,
    installCount: 0,
    weeklyInstalls: 0,
    version: "0.1.0",
    lastUpdated: now,
    createdAt: now,
    tags: ["tinybird", "analytics", "clickhouse", "real-time", "streaming"],
    features: ["Analytics queries", "SQL queries", "Real-time data", "Data sources", "Pipes", "Tokens"],
    githubUrl: "https://github.com/tinybirdco/mcp-tinybird",
    docsUrl: "https://www.tinybird.co/docs",
    iconBg: "#22C55E",
    verified: true,
    trending: false,
    featured: false,
    compatibility: ["Claude", "GPT", "Open Source"],
    npmPackage: "mcp-tinybird",
  },
];

async function seed() {
  console.log("🌱 Seeding database...\n");

  // Clear existing data
  console.log("Clearing existing data...");
  await db.delete(reviews).execute();
  await db.delete(userConnections).execute();
  await db.delete(toolSubmissions).execute();
  await db.delete(tools).execute();
  await db.delete(categories).execute();

  // Seed categories
  console.log("Seeding categories...");
  for (const cat of SEED_CATEGORIES) {
    await db.insert(categories).values(cat).onConflictDoNothing();
  }
  console.log(`  ✓ ${SEED_CATEGORIES.length} categories`);

  // Seed tools
  console.log("Seeding tools...");
  for (const tool of SEED_TOOLS) {
    await db.insert(tools).values(tool).onConflictDoNothing();
  }
  console.log(`  ✓ ${SEED_TOOLS.length} tools`);

  console.log("\n✅ Seed complete!");
  console.log(`   Categories: ${SEED_CATEGORIES.length}`);
  console.log(`   Tools: ${SEED_TOOLS.length}`);
  process.exit(0);
}

// Need to import these for the clear step
import { reviews, userConnections, toolSubmissions } from "./schema";

seed().catch((err) => {
  console.error("❌ Seed failed:", err);
  process.exit(1);
});
